# 데이터 인코딩

## label encoding
문자열 피쳐를 코드형 숫자값으로 변환해 주는 인코딩 방식

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'name':['냉장고','TV','세탁기'],
                  'price':[13,23,12]})

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   price   3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 176.0+ bytes


In [4]:
from sklearn import preprocessing

In [5]:
le = preprocessing.LabelEncoder() # 객체생성

In [7]:
le.fit(df.name) # 매핑 테이블 생성

LabelEncoder()

In [8]:
le.transform(df.name)
# le.fit_transform(df.name) 으로 한번에 실행 가능
# fit과 transform를 따로 사용하는 이유 : 해당 인코딩을 반복 사용 가능하기 때문

array([1, 0, 2])

In [11]:
le.classes_

array(['TV', '냉장고', '세탁기'], dtype=object)

In [13]:
le.inverse_transform([0,2,0])

array(['TV', '세탁기', 'TV'], dtype=object)

In [9]:
df['id'] = le.transform(df.name)

In [10]:
df

name  price  id
0  냉장고     13   1
1   TV     23   0
2  세탁기     12   2

In [ ]:
df2 = df.copy()

## one-hot encoding

In [14]:
# OneHotEncdoer 방법

ohe = preprocessing.OneHotEncoder()

In [20]:
ohe.fit_transform(df.name.values.reshape(-1,1)).toarray()

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [21]:
# LabelBinarizer 방법

lb = preprocessing.LabelBinarizer()

In [23]:
lb.fit_transform(df.name)

array([[0, 1, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [24]:
# 가장 쉬운 방법 : pandas.get_dumies()

pd.get_dummies(df)

price  id  name_TV  name_냉장고  name_세탁기
0     13   1        0         1         0
1     23   0        1         0         0
2     12   2        0         0         1

In [25]:
pd.get_dummies(df.name)

TV  냉장고  세탁기
0   0    1    0
1   1    0    0
2   0    0    1

# 피쳐 스케일링과 정규화

In [26]:
from sklearn.datasets import load_iris

In [28]:
iris = load_iris()

iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)

In [29]:
iris_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

## StandardScaler

In [30]:
ss = preprocessing.StandardScaler()

In [32]:
ss.fit(iris_df)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [36]:
iris_ss = pd.DataFrame(ss.transform(iris_df),columns=iris_df.columns)

In [37]:
iris_ss.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.690315e-15     -1.842970e-15      -1.698641e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)  
count      1.500000e+02  
mean      -1.409243e-15  
std        1.003350e+00  
min       -1.447076e+00  
25%       -1.183812e+00  
50%        1.325097e-01  
75%        7.906707e-01  
max        1.712096e+00

## MinMaxScaler

In [38]:
mms = preprocessing.MinMaxScaler()

In [39]:
mms.fit(iris_df)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [40]:
iris_mms = pd.DataFrame(mms.transform(iris_df), columns=iris_df.columns)

In [41]:
iris_mms.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000